### ISSUE TITLE
[Request] Allow addon to work when called from other sources and not rely on UI

### ISSUE THREAD

**Issue by ninthwalker** [TheGeneticsGuy/Mass_Crafting_Assist#2]
Currently, you get info from the professions UI for various functions.
I craft via macro's a lot, and some of them do not need to open or have the pofessions UI open. This is also useful due to crafting window memory leak that I don't think has been fixed yet by Blizzard. So having the crafting window closed helps when doing mass crafting like this addon is designed for.

It would be nice if you could get the info needed via other api calls or check if the profession window is not open, to then fall back to a different api since the macro will not 'load' the mat into the crafting interface.

Example:
This will fail if not loaded via crafting window: `ProfessionsFrame.CraftingPage.SchematicForm:GetTransaction().salvageItem;`
https://github.com/TheGeneticsGuy/Mass_Salvage_Assist/blob/main/MSA_Crafting.lua#L189

Instead, maybe check if that 'item.debugItemID' is nil, fall back on getting the current craft id via a different api or something, and if that is also still nil, print error that item can not be identified instead of a LUA error.
``

Thanks for your addon!

Edit:
So i poked around a little and i'm not sure if it's possible, but figured I would toss it to you to see if you knew. Checked a couple api calls,  and wasn't able to see the material being converted, only the spell that was doing it. Have a workaround idea for that, but don't think it would be worth adding for people like me. My workaround idea was to get all mats that are valid for the current crafting operation, save the count, check those counts again after one cast, and whatever mat went down was the one being used. lol =/

**Comment by Sirius5783** [comment]
I have a macro that can do mass crafting as a button to press, but it has the stack problem which this addon have solved. I used to press another button with a packing bag marco each time first. The macro code is below, maybe you guys could find something useful from there. 
`/use item:211802
/run for bg=0,5 do for s=1,C_Container.GetContainerNumSlots(bg) do local lnk=ItemLocation:CreateFromBagAndSlot(bg,s) if lnk:IsValid() and C_Item.GetItemID(lnk) == 211802 then C_TradeSkillUI.CraftSalvage(430315,1000,lnk) return end end end`

**Comment by TheGeneticsGuy** [comment]
So, I was unaware of the profession window memory leak - someone just reported to me that my addon was taking up like 5GB of addon memory after a few hours of nonstop crafting - I was like wuh!? I couldn't figure out as to why as I didn't see myself introducing any kind of crazy memory leak like that lol...

This is really good to know though. In terms of getting IDs, I can probably work something out to this, I just went the easy way.

However, mass crafting even with profession window closed? This is the first I've heard of this... I'll tinker around and see what I find regarding this. Thanks for the heads up on all of this. I like the idea of not having to rely on the source. I will say, that's definitely appealing. I find that the profession window, if I am doing ultra fast speed milling when in a capital city can get REALLY slow with profession window open. I have to leave the city. I wonder if it would be effective without.

**Comment by TheGeneticsGuy** [comment]
So I think I have some good news for you guys... but I want to test a little more so standby lol

**Comment by TheGeneticsGuy** [comment]
Ok, so let me tell you my strategy on getting the item_id, since you are right, there doesn't seem to be any API to obtain it when window isn't open, and I dug everywhere. I even went into the [Blizz InterfaceCode](https://github.com/tomrus88/BlizzardInterfaceCode) to dig through Blizz's own code to find something... nothing.

Ok, so if I can't do it that way instead, what I do is see the /etrace and see if I can find a pattern, which is exactly what I did. I know what the casting spell is of the profession, so when the event fires "TRADE_SKILL_CRAFT_BEGIN" and it matches my salvaging spell, I know that the next time the event "ITEM_COUNT_CHANGED" fires, it is going to be the reagent used in the craft, as the reagent is used BEFORE you loot the newly crafted item. This event shows the item number. I store that number for access globally and when it comes to combining stacks again, I know which item I am salvaging and what to combine again. No need to create complicated tables.

Anyway, I have it pretty well tested but I am going to tinker around a little more. But yes, I have it fully working WITHOUT the profession window now. I kind of am curious about expanding the use of macros for people, but that just opens up another whole can of worms... I might just leave it as a nice feature for the few "in-the-know" until I decide what to do...

**Comment by ninthwalker** [comment]
Nice. I also was looking through etrace but didn't think to check the order it fired off those events since they were so close to each other. Would be cool if it can detect it that way. I use a WA i made that cycles through all the Thaumaturgy mats of choosing so it can be done with just one button and it loads via mixin (similar to the macro @Sirius5783 posted) so does not need the UI. I was catching the crafting ending event, and having the bags resstack so it would auto fix the stacking issue. Your way of re-stacking during the crafting is better though.

The WA code for ref and some of my notes I was using for it. Utilizes re-keybinding of macro functionality and things like that. Specific for Thaumaturgy, but if you ever did want some ideas for future integration could take a look. I could see some kind of auto-keybind attaching to whatever the current craft is being useful or something down the line.
 [wow_thaumaturgy](https://github.com/ninthwalker/wow_thaumaturgy)
 
 Thanks for looking in to it.
 
 Edit:
 Looked at etrace again after your suggestion, maybe you are able to grab correct order or maybe etrace's GUI doesn't show the real order that code would get. Here's a sample of what i see, and in this case the material being used was Mycobloom R2, but it show's last in etrace for  ITEM_COUNT_CHANGED (210797)
 
 
![image](https://github.com/user-attachments/assets/0a6f0545-9dbe-44ca-8ef8-f9cabeac990c)

Edit2:
I take it back, it is just a graphical etrace thing it looks like. When i grabbed the event in code, the mat used is returned first every time. Nice find.
![image](https://github.com/user-attachments/assets/b0e9e9a1-6f21-4677-9b04-813ad5c0b763)

**Comment by TheGeneticsGuy** [comment]
Ya, I have a couple other tricks up my sleeve lol - I think I am going to drop something you'll appreciate but it's going to have to be tomorrow, just not enough time tonight to finish.

**Comment by TheGeneticsGuy** [comment]
Oh man the amount of hackery I have to do to get this working without the professions window closed is kind of annoying, but I am getting it working lol.

I found this weird bug with the CraftSalvage function where it will just sometimes swap stacks. This is even with the addon disabled. I was trying to isolate a bug I thought was on my end, but nope, I'll have a stack of say 900 herbs left, and another stack with like 50. I activate the `C_TradeSkillUI.CraftSalvage` function and it starts - then boom, halfway through, with zero further input from me, it just swaps to a different bag slot, brings down my smaller bag, then errors out since stack is now empty lol.

I had to write some complicated listening logic to refresh the C_TradeSkillUI.CraftSalvage to ensure it sticks to the one bag every so often, without being too spammy... but this meant I now had to do some other shenannigans to ensure my item-ID was correct, which I found that what I discussed above is correct 99% of the time, but other times it goes out of order, so now I have an edge case failure that will hit every few thousand items salvaged lol - But I got it all smoothed out! I am kind of amazed it's running as smoothly now - gonna test it a little more, but geesh, this was supposed to be a super simple small addon when I posted it 2 days ago and it's turned into this bigger thing lol.

I've got lots of people on my Guild Roster Manager discord constantly asking about status of work on some things I was building for that, but they don't know here I am distracted with this little side project lol

**Comment by ninthwalker** [comment]
That's too bad it's turned out to be more more complicated and buggy than initially thought. Honestly, this is more of an edge case, i'm sure most people just use the crafting window. Feel free to drop this or put it off and do whatever other priority real life or wow-related stuff you have going on. This was more just a nice-to-have request, so I appreciate how much you already have looked into it to get it to work. =)
Happy Halloween!

**Comment by TheGeneticsGuy** [comment]
I also realized I completely overthought finding the item ID -- using the addon OUTSIDE of the profession window requires macro input. Macro input requires you to know the item_id. I could have just taken the itemID from the macro input lol.

**Comment by ninthwalker** [comment]
The code i use doesn't have the id in the macro, as I use one macro that kicks off the weak aura i wrote, which then decides on the the fly which material to actual use for that Thaumaturgy cast. The example Sirius has above had it in there, but then he is having to either have multiple different macro's with different hardcoded ID's or always be updating the one macro.

I thought about integrating your code into the WA, since the WA knows the ID's it's using obviously, but thought it would be nice to just use your addon to do what it was doing as well. Since there is no easy API call that returns the ID we are after, this all might just be a bit too much effort to try and do in your addon. Can just keep it the way it is for using the crafting window.

Edit: oh, that just gave me a good idea too. I could have the code I use, just update one macro with the current ID and then use your code to just read that macro for the id each time. That would just be a little custom code mod to your code I could do.

I'll be honest, i'm not an addon dev, just a dabbler with code/scripts. If there was a way to write a global variable and read that instead of the macro, I could do that as well. The scoping of variables in lua and accessing across addon space I never done really.

**Comment by TheGeneticsGuy** [comment]
@ninthwalker and @Sirius5783  

Macro support has been added.

**Slash command** - `/msa`

*Craft without the profession window by using macros!*

    - Example - Mass Mill Hochenblume:
    - /msa craft recipe_id item_id
    - /msa craft 382981 191461
    -
    - You can also get help:
    - /msa help
    
 Replace your lengthy macro scripts with Mass Salvage Assist macros to do the same thing. Looks a little cleaner too! Also, it will in most cases report back incorrect entries, like if you add a recipe to the macro that isn't actually a slavage spell it will tell you, or if the itemID is not valid... 
 
 Download 1.0.4 and you can work with all professions that salvage without needing to open the profession window! Thanks for the suggestion! I'll leave this open for you to report back that everything is work alright before I close it.

**Comment by ninthwalker** [comment]
Dude, you're a pro. Great idea adding the slash and giving it the id that way. We were originally way over-thinking it (or i was at least) trying to automatically get the ID. With the slash comand I can call it from my WA or it can be used in other macros/scripts now as well.

Tested it out and it's working great.
One thing maybe to check for or add as an error output when /msa is used. It still needs the checkbox originally checked in the UI. I forgot to do that and the cmd didn't output an error, but then wasn't stacking either till I realized i didn't check the box in the ui. Alternatively, if the slash cmd is used, maybe the code for checking for the checkbox is not even needed as you are specifically telling it you want to mass craft using the addon.

Thanks for adding this in, it's great.

**Comment by TheGeneticsGuy** [comment]
Ah ya, I forgot about that lol - Actually my next step is to add a button to "Create Macro" to the professions page so people can load an item, then create a macro easily for each of their professions they use

**Comment by Sirius5783** [comment]
Thanks for your effort for all this! I'd like to say that lazyness is the engine for human to progress or at least an encouragement to make a tool that can reduce ppl's workload haha. I had tried several methods to auto-select the next stack of given item id to craft and how to craft more than 1000 items with one click(within the ToS) before this addon showed, the former failed because something to with a call to C_TradeSkillUI.CraftSalvage function can only be user's input not addon, the latter ended up with about 10 macros to press while i was doing thaumaturgy haha, press 1 to pack bags and press 2/3/4/5......

**Comment by TheGeneticsGuy** [comment]
Haha ya - this is actually how it really started for me. I was super annoyed with the stacking bug, and while this cost me so much more time to build than that stacking bug ever did, I thought to myself, "Well, I'm a programmer, let's see if this can be fixed in an addon," and here we are.

Why keep something this useful to others private? lol

Anyway, I have some other ideas on expanding this a little further I will circle back to soon.
