### ISSUE TITLE
support for 1 button for multiple salvaging

### ISSUE THREAD

**Issue by finegorko** [TheGeneticsGuy/Mass_Crafting_Assist#4]
for example 1 macro will contain

/msa craft 2314123 43214312
/msa craft 2314123 42314132
/msa craft  32451 43214312
/msa craft  321523 43214312

and it will salvaging in order

just add if GetItemCount(targetitem) >= reqItemForSalvage then break, something like this 

it will be very convenient for 1 button several operations

and redesign please timer UI because its super large for text

**Comment by TheGeneticsGuy** [comment]
Ya, I have thought about this -- Basically queing up salvaging. It's definitely doable. I kind of wanted to implement one other feature first before I add in the queuing though. I was going to implement a way to auto-create a macro with the push of a button... Once I get that out I'll probably update a way to queue up. I like the idea though.

For context further, I was going to implement a way to salvage not just the 1 item type, but all item types, but to do so would require a table created of all the types... Once I get some time, probably this weekend I'll see what API is available in determining them all, or if I am just going to need to do a one-time scan on creation of the macro or something. We'll see.

Regarding the timer, I'll get to it eventually. It seems large now because I needed the room for the checkboxes. I'll probably have a transform button eventually I'll add. I'll keep this open til it all gets done. Thanks!

**Comment by finegorko** [comment]
thanks sir will wait
